import pandas as pd

df = pd.read_csv("data/release/banlegit_cite_dataset.csv")

# Filter for FABRICATED
fab_df = df[df["label"] == "FABRICATED"]

print(f"Total rows in dataset: {len(df)}")
print(f"Total FABRICATED cases: {len(fab_df)}")

# Generate markdown output
md_content = f"# Fabricated Cases generated by Gemini\n\nTotal Count: **{len(fab_df)}**\n\n"

for idx, row in fab_df.iterrows():
    md_content += f"### {row['citation_id']}\n"
    md_content += f"- **Citation:** {row['citation']}\n"
    md_content += f"- **Context:** {row['context']}\n"
    md_content += f"- **Source:** {row['source']}\n"
    md_content += f"- **Fabrication Type:** {row['fabrication_type']}\n"
    md_content += f"- **Extracted URL:** {row['extracted_url']}\n\n"

output_path = "fabricated_cases_by_gemini.md"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(md_content)

print(f"Saved {len(fab_df)} fabricated cases to {output_path}")
